/**
 * In-memory incident store for the SynaPath AI dashboard.
 * In production, this would be backed by UiPath Data Service or a database.
 * Pre-seeded with demo incidents for the hackathon demo.
 */

export interface StoredIncident {
  id: string;
  maestroCaseId?: string;
  title: string;
  source: string;
  status: 'active' | 'resolved' | 'pending_human' | 'investigating';
  severity: 'low' | 'medium' | 'high' | 'critical';
  agentActivity: string[];
  rootCause?: string;
  proposedSolution?: string;
  auditTrail: string[];
  metrics: { cpu: string; memory: string; latency: string };
  codeSnippet?: string;
  terminalLog?: string;
  diagnosticPlan?: string;
  createdAt: string;
  updatedAt: string;
}

// Pre-seeded demo incidents
const seedIncidents: StoredIncident[] = [
  {
    id: 'INC001',
    title: 'Database connection error in Production API',
    source: 'MonitoringAlert',
    status: 'investigating',
    severity: 'critical',
    metrics: { cpu: '45%', memory: '2GB', latency: '500ms' },
    agentActivity: [
      'Intake & Triage Agent: Categorized as critical.',
      'Knowledge & Context Agent: Querying KB for similar issues.',
      'Diagnostic & Root Cause Agent: Analyzing logs.',
    ],
    auditTrail: [
      'Incident created by monitoring system.',
      'Intake Agent initiated case.',
      'Knowledge Agent started search.',
    ],
    terminalLog: `> Connecting to Production DB cluster...\n> Error: Connection Timeout on port 5432\n> Diagnostic Agent: Analyzing pgbouncer logs...\n> Found IP block on firewall rule #8492.`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'INC002',
    title: 'Web server latency spike - US-East',
    source: 'MonitoringAlert',
    status: 'pending_human',
    severity: 'high',
    metrics: { cpu: '98%', memory: '15GB', latency: '2500ms' },
    agentActivity: [
      'Intake & Triage Agent: Prioritized as high.',
      'Diagnostic & Root Cause Agent: Identified potential memory leak.',
      'Action & Remediation Agent: Proposed restart, awaiting approval.',
    ],
    rootCause: 'Memory leak in Apache process causing massive swap usage.',
    proposedSolution: 'Restart Apache service and deploy temporary memory limit override.',
    auditTrail: [
      'Monitoring alert received.',
      'Diagnostic Agent identified cause.',
      'Approval requested for remediation.',
    ],
    terminalLog: `> Analyzing top processes...\n> PID 4921 (apache2) consuming 98% CPU\n> Memory tracing initiated...\n> Memory leak confirmed in module mod_proxy.\n> Action Agent: Preparing restart script.`,
    codeSnippet: `#!/bin/bash\n# Remediation Script Generated by Action Agent\nsudo systemctl restart apache2\nsudo systemctl status apache2 --no-pager\necho "Service restarted and metrics stabilizing."`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'INC003',
    title: 'Minor CPU utilization increase on dev server',
    source: 'ITSM',
    status: 'resolved',
    severity: 'low',
    metrics: { cpu: '70%', memory: '4GB', latency: '40ms' },
    agentActivity: [
      'Intake & Triage Agent: Classified as low.',
      'Diagnostic & Root Cause Agent: Detected background job.',
      'Action & Remediation Agent: Optimized cron job schedule.',
    ],
    rootCause: 'Inefficient scheduled cron job colliding with DB backup',
    proposedSolution: 'Adjust cron job frequency and resource limits.',
    auditTrail: [
      'Incident resolved automatically.',
      'Communication Agent updated ITSM ticket.',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'INC004',
    title: 'Authentication service intermittent failures',
    source: 'MonitoringAlert',
    status: 'active',
    severity: 'critical',
    metrics: { cpu: '85%', memory: '8GB', latency: '1200ms' },
    agentActivity: [
      'Intake & Triage Agent: High priority.',
      'Diagnostic & Root Cause Agent: Suspects recent deploy impact.',
      'Knowledge & Context Agent: Gathering rollback procedures.',
    ],
    auditTrail: [
      'User reports received.',
      'Incident escalated due to impact.',
      'Agents collaborating.',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// The actual store - a Map keyed by incident ID
const incidents: Map<string, StoredIncident> = new Map();

// Seed on first import
seedIncidents.forEach((inc) => incidents.set(inc.id, inc));

let incidentCounter = 5; // Next ID after seed data

export function getAllIncidents(): StoredIncident[] {
  return Array.from(incidents.values()).sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
}

export function getIncident(id: string): StoredIncident | undefined {
  return incidents.get(id);
}

export function createIncident(data: Partial<StoredIncident>): StoredIncident {
  const id = `INC${String(incidentCounter++).padStart(3, '0')}`;
  const now = new Date().toISOString();
  const incident: StoredIncident = {
    id,
    title: data.title || 'New Incident',
    source: data.source || 'Dashboard',
    status: 'investigating',
    severity: (data.severity as StoredIncident['severity']) || 'medium',
    agentActivity: [],
    auditTrail: [`[${new Date().toLocaleTimeString()}] Incident created via SynaPath Dashboard.`],
    metrics: data.metrics || { cpu: 'N/A', memory: 'N/A', latency: 'N/A' },
    createdAt: now,
    updatedAt: now,
  };
  incidents.set(id, incident);
  return incident;
}

export function updateIncident(id: string, updates: Partial<StoredIncident>): StoredIncident | undefined {
  const incident = incidents.get(id);
  if (!incident) return undefined;

  // Append to arrays instead of replacing
  if (updates.agentActivity) {
    incident.agentActivity = [...incident.agentActivity, ...updates.agentActivity];
    delete updates.agentActivity;
  }
  if (updates.auditTrail) {
    incident.auditTrail = [...incident.auditTrail, ...updates.auditTrail];
    delete updates.auditTrail;
  }

  Object.assign(incident, updates, { updatedAt: new Date().toISOString() });
  incidents.set(id, incident);
  return incident;
}
