import { prisma } from './prisma';

export interface StoredIncident {
  id: string;
  maestroCaseId?: string;
  title: string;
  source: string;
  status: 'active' | 'resolved' | 'pending_human' | 'investigating';
  severity: 'low' | 'medium' | 'high' | 'critical';
  agentActivity: string[];
  rootCause?: string;
  proposedSolution?: string;
  auditTrail: string[];
  metrics: { cpu: string; memory: string; latency: string };
  codeSnippet?: string;
  terminalLog?: string;
  diagnosticPlan?: string;
  createdAt: string;
  updatedAt: string;
}

const seedIncidents: StoredIncident[] = [
  {
    id: 'INC001',
    title: 'Database connection error in Production API',
    source: 'MonitoringAlert',
    status: 'pending_human',
    severity: 'critical',
    metrics: { cpu: '45%', memory: '2GB', latency: '500ms' },
    agentActivity: [
      'Intake & Triage Agent: Categorized as critical.',
      'Knowledge & Context Agent: Querying KB for similar issues.',
      'Diagnostic & Root Cause Agent: Analyzing logs.',
      'Action & Remediation Agent: Generated fix, awaiting approval.',
    ],
    auditTrail: [
      'Incident created by monitoring system.',
      'Intake Agent initiated case.',
      'Knowledge Agent started search.',
      'Approval requested for remediation.',
    ],
    rootCause: 'Firewall rule #8492 blocking access to the Production DB cluster.',
    proposedSolution: 'Remove the restrictive firewall rule to restore database connectivity.',
    terminalLog: `> Connecting to Production DB cluster...\n> Error: Connection Timeout on port 5432\n> Diagnostic Agent: Analyzing pgbouncer logs...\n> Found IP block on firewall rule #8492.`,
    codeSnippet: `#!/bin/bash\n# Remediation Script Generated by Action Agent\n# Removes IP block from firewall\naws ec2 revoke-security-group-ingress --group-id sg-0123456789 --protocol tcp --port 5432 --cidr 10.0.0.0/8\necho "Firewall rule updated. Database connection restored."`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'INC002',
    title: 'Web server latency spike - US-East',
    source: 'MonitoringAlert',
    status: 'pending_human',
    severity: 'high',
    metrics: { cpu: '98%', memory: '15GB', latency: '2500ms' },
    agentActivity: [
      'Intake & Triage Agent: Prioritized as high.',
      'Diagnostic & Root Cause Agent: Identified potential memory leak.',
      'Action & Remediation Agent: Proposed restart, awaiting approval.',
    ],
    rootCause: 'Memory leak in Apache process causing massive swap usage.',
    proposedSolution: 'Restart Apache service and deploy temporary memory limit override.',
    auditTrail: [
      'Monitoring alert received.',
      'Diagnostic Agent identified cause.',
      'Approval requested for remediation.',
    ],
    terminalLog: `> Analyzing top processes...\n> PID 4921 (apache2) consuming 98% CPU\n> Memory tracing initiated...\n> Memory leak confirmed in module mod_proxy.\n> Action Agent: Preparing restart script.`,
    codeSnippet: `#!/bin/bash\n# Remediation Script Generated by Action Agent\nsudo systemctl restart apache2\nsudo systemctl status apache2 --no-pager\necho "Service restarted and metrics stabilizing."`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'INC003',
    title: 'Minor CPU utilization increase on dev server',
    source: 'ITSM',
    status: 'resolved',
    severity: 'low',
    metrics: { cpu: '70%', memory: '4GB', latency: '40ms' },
    agentActivity: [
      'Intake & Triage Agent: Classified as low.',
      'Diagnostic & Root Cause Agent: Detected background job.',
      'Action & Remediation Agent: Optimized cron job schedule.',
    ],
    rootCause: 'Inefficient scheduled cron job colliding with DB backup',
    proposedSolution: 'Adjust cron job frequency and resource limits.',
    auditTrail: [
      'Incident resolved automatically.',
      'Communication Agent updated ITSM ticket.',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'INC004',
    title: 'Authentication service intermittent failures',
    source: 'MonitoringAlert',
    status: 'pending_human',
    severity: 'critical',
    metrics: { cpu: '85%', memory: '8GB', latency: '1200ms' },
    agentActivity: [
      'Intake & Triage Agent: High priority.',
      'Diagnostic & Root Cause Agent: Suspects recent deploy impact.',
      'Knowledge & Context Agent: Gathering rollback procedures.',
      'Action & Remediation Agent: Rollback plan generated, awaiting human approval.',
    ],
    auditTrail: [
      'User reports received.',
      'Incident escalated due to impact.',
      'Agents collaborating.',
      'Approval required for production rollback.',
    ],
    rootCause: 'Recent deployment (v2.1.4) introduced a connection pool exhaustion bug in the auth service.',
    proposedSolution: 'Roll back the auth service deployment to stable version v2.1.3.',
    terminalLog: `> Checking auth service health...\n> Error: Connection Pool Exhausted\n> Diagnostic Agent: Correlating with recent deployments...\n> Found deployment v2.1.4 executed 15 minutes ago.`,
    codeSnippet: `#!/bin/bash\n# Remediation Script Generated by Action Agent\n# Rolls back auth service in Kubernetes\nkubectl rollout undo deployment/auth-service -n prod-auth\nkubectl rollout status deployment/auth-service -n prod-auth\necho "Rollback to v2.1.3 complete. Auth service stabilized."`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

function serialize(inc: StoredIncident): any {
  return {
    ...inc,
    agentActivity: JSON.stringify(inc.agentActivity || []),
    auditTrail: JSON.stringify(inc.auditTrail || []),
    metrics: JSON.stringify(inc.metrics || { cpu: 'N/A', memory: 'N/A', latency: 'N/A' }),
  };
}

function deserialize(inc: any): StoredIncident {
  return {
    ...inc,
    agentActivity: inc.agentActivity ? JSON.parse(inc.agentActivity) : [],
    auditTrail: inc.auditTrail ? JSON.parse(inc.auditTrail) : [],
    metrics: inc.metrics ? JSON.parse(inc.metrics) : { cpu: 'N/A', memory: 'N/A', latency: 'N/A' },
    createdAt: inc.createdAt.toISOString(),
    updatedAt: inc.updatedAt.toISOString(),
  };
}

export async function seedDatabase() {
  const count = await prisma.incident.count();
  if (count === 0) {
    for (const inc of seedIncidents) {
      await prisma.incident.create({ data: serialize(inc) });
    }
  }
}

export async function getAllIncidents(): Promise<StoredIncident[]> {
  await seedDatabase();
  const incidents = await prisma.incident.findMany({
    orderBy: { createdAt: 'desc' }
  });
  return incidents.map(deserialize);
}

export async function getIncident(id: string): Promise<StoredIncident | undefined> {
  const incident = await prisma.incident.findUnique({ where: { id } });
  return incident ? deserialize(incident) : undefined;
}

export async function createIncident(data: Partial<StoredIncident>): Promise<StoredIncident> {
  const count = await prisma.incident.count();
  const id = `INC${String(count + 5).padStart(3, '0')}`; // simple ID generator
  
  const incidentData = {
    id,
    title: data.title || 'New Incident',
    source: data.source || 'Dashboard',
    status: 'investigating',
    severity: data.severity || 'medium',
    agentActivity: JSON.stringify([]),
    auditTrail: JSON.stringify([`[${new Date().toLocaleTimeString()}] Incident created via SynaPath Dashboard.`]),
    metrics: JSON.stringify(data.metrics || { cpu: 'N/A', memory: 'N/A', latency: 'N/A' }),
  };

  const created = await prisma.incident.create({ data: incidentData });
  return deserialize(created);
}

export async function updateIncident(id: string, updates: Partial<StoredIncident>): Promise<StoredIncident | undefined> {
  const incident = await prisma.incident.findUnique({ where: { id } });
  if (!incident) return undefined;

  const currentInc = deserialize(incident);
  
  if (updates.agentActivity) {
    currentInc.agentActivity = [...currentInc.agentActivity, ...updates.agentActivity];
    delete updates.agentActivity;
  }
  if (updates.auditTrail) {
    currentInc.auditTrail = [...currentInc.auditTrail, ...updates.auditTrail];
    delete updates.auditTrail;
  }

  const newInc = { ...currentInc, ...updates };

  const updated = await prisma.incident.update({
    where: { id },
    data: {
      maestroCaseId: newInc.maestroCaseId,
      title: newInc.title,
      source: newInc.source,
      status: newInc.status,
      severity: newInc.severity,
      rootCause: newInc.rootCause,
      proposedSolution: newInc.proposedSolution,
      codeSnippet: newInc.codeSnippet,
      terminalLog: newInc.terminalLog,
      diagnosticPlan: newInc.diagnosticPlan,
      agentActivity: JSON.stringify(newInc.agentActivity),
      auditTrail: JSON.stringify(newInc.auditTrail),
      metrics: JSON.stringify(newInc.metrics),
    }
  });

  return deserialize(updated);
}
