"use client";

import React, { useState, useEffect } from 'react';
import { PieChart, TrendingDown, Clock, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';
import { motion } from 'framer-motion';

const AnalyticsPage = () => {
  const [metrics, setMetrics] = useState({
    mttr: '...',
    autonomousRate: '...',
    preventativeActions: 0,
    health: { usEast: 99.99, euWest: 99.95, apSouth: 100.00 }
  });

  useEffect(() => {
    const fetchMetrics = async () => {
      try {
        const res = await fetch('/api/metrics');
        if (res.ok) {
          const data = await res.json();
          setMetrics(data.analytics);
        }
      } catch (err) {
        console.error('Failed to fetch analytics metrics', err);
      }
    };

    fetchMetrics();
    const interval = setInterval(fetchMetrics, 2000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-[calc(100vh-64px)] p-8 bg-background text-foreground relative">
      <div className="absolute top-0 left-0 w-full h-96 z-0 overflow-hidden pointer-events-none">
        <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=2000&q=80" alt="Data Analytics" className="w-full h-full object-cover opacity-20 mix-blend-screen" />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-background"></div>
      </div>
      <div className="max-w-7xl mx-auto relative z-10">
        <header className="mb-10">
          <h1 className="text-4xl font-bold flex items-center gap-3">
            <PieChart className="w-10 h-10 text-primary" />
            Platform Analytics
          </h1>
          <p className="text-secondary mt-2 text-lg">Real-time performance and savings metrics generated by SynaPath AI.</p>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
          <motion.div 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="bg-card/50 backdrop-blur-md border border-border rounded-2xl p-6 shadow-xl relative overflow-hidden"
          >
            <div className="absolute -right-6 -top-6 w-32 h-32 bg-primary/10 rounded-full blur-2xl"></div>
            <div className="flex justify-between items-start mb-4">
              <div className="p-3 bg-primary/20 text-primary rounded-xl"><Clock className="w-6 h-6" /></div>
              <span className="flex items-center text-success text-sm font-bold bg-success/10 px-2 py-1 rounded-full"><TrendingDown className="w-4 h-4 mr-1"/> 84%</span>
            </div>
            <h3 className="text-secondary font-medium mb-1">Mean Time To Resolution (MTTR)</h3>
            <p className="text-4xl font-bold transition-all duration-500">{metrics.mttr}</p>
            <p className="text-xs text-secondary mt-4">Industry average: 45m 30s</p>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
            className="bg-card/50 backdrop-blur-md border border-border rounded-2xl p-6 shadow-xl relative overflow-hidden"
          >
            <div className="absolute -right-6 -top-6 w-32 h-32 bg-success/10 rounded-full blur-2xl"></div>
            <div className="flex justify-between items-start mb-4">
              <div className="p-3 bg-success/20 text-success rounded-xl"><CheckCircle2 className="w-6 h-6" /></div>
            </div>
            <h3 className="text-secondary font-medium mb-1">Autonomous Resolution Rate</h3>
            <p className="text-4xl font-bold transition-all duration-500">{metrics.autonomousRate}%</p>
            <p className="text-xs text-secondary mt-4">Incidents fixed without human intervention</p>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
            className="bg-card/50 backdrop-blur-md border border-border rounded-2xl p-6 shadow-xl relative overflow-hidden"
          >
            <div className="absolute -right-6 -top-6 w-32 h-32 bg-warning/10 rounded-full blur-2xl"></div>
            <div className="flex justify-between items-start mb-4">
              <div className="p-3 bg-warning/20 text-warning rounded-xl"><AlertTriangle className="w-6 h-6" /></div>
            </div>
            <h3 className="text-secondary font-medium mb-1">Preventative Actions</h3>
            <p className="text-4xl font-bold transition-all duration-500">{metrics.preventativeActions.toLocaleString()}</p>
            <p className="text-xs text-secondary mt-4">Issues caught before impacting production</p>
          </motion.div>
        </div>

        <motion.div 
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}
          className="bg-card border border-border rounded-2xl p-8 shadow-xl"
        >
          <div className="flex items-center gap-3 mb-6">
            <ShieldCheck className="w-8 h-8 text-indigo-400" />
            <h2 className="text-2xl font-bold">System Health Matrix</h2>
          </div>
          
          <div className="space-y-6">
            <div>
              <div className="flex justify-between mb-2">
                <span className="font-medium">US-East Cluster (Core API)</span>
                <span className={`font-mono transition-colors duration-500 ${metrics.health.usEast < 99 ? 'text-danger' : 'text-success'}`}>{metrics.health.usEast}%</span>
              </div>
              <div className="w-full bg-background rounded-full h-3 border border-border">
                <div className={`h-2.5 rounded-full transition-all duration-1000 ${metrics.health.usEast < 99 ? 'bg-danger' : 'bg-success'}`} style={{ width: `${metrics.health.usEast}%` }}></div>
              </div>
            </div>
            <div>
              <div className="flex justify-between mb-2">
                <span className="font-medium">EU-West Cluster (Data Lake)</span>
                <span className={`font-mono transition-colors duration-500 ${metrics.health.euWest < 95 ? 'text-warning' : 'text-success'}`}>{metrics.health.euWest.toFixed(2)}%</span>
              </div>
              <div className="w-full bg-background rounded-full h-3 border border-border">
                <div className={`h-2.5 rounded-full transition-all duration-1000 ${metrics.health.euWest < 95 ? 'bg-warning' : 'bg-success'}`} style={{ width: `${metrics.health.euWest}%` }}></div>
              </div>
            </div>
            <div>
              <div className="flex justify-between mb-2">
                <span className="font-medium">AP-South Cluster (Edge Cache)</span>
                <span className="text-success font-mono">{metrics.health.apSouth.toFixed(2)}%</span>
              </div>
              <div className="w-full bg-background rounded-full h-3 border border-border">
                <div className="bg-success h-2.5 rounded-full transition-all duration-1000" style={{ width: `${metrics.health.apSouth}%` }}></div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default AnalyticsPage;
