"use client";

import React, { useState, useEffect } from 'react';
import { CheckCircle, AlertTriangle, XCircle, MoreHorizontal, UserCheck, Activity, Brain, Handshake, Mail, Zap, Terminal, Code2, Info } from 'lucide-react';

interface Incident {
  id: string;
  title: string;
  status: 'active' | 'resolved' | 'pending_human' | 'investigating';
  severity: 'low' | 'medium' | 'high' | 'critical';
  agentActivity: string[];
  rootCause?: string;
  proposedSolution?: string;
  auditTrail: string[];
  metrics: { cpu: string; memory: string; latency: string };
  codeSnippet?: string;
  terminalLog?: string;
}

const mockIncidents: Incident[] = [
  {
    id: 'INC001',
    title: 'Database connection error in Production API',
    status: 'investigating',
    severity: 'critical',
    metrics: { cpu: '45%', memory: '2GB', latency: '500ms' },
    agentActivity: ['Intake & Triage Agent: Categorized as critical.', 'Knowledge & Context Agent: Querying KB for similar issues.', 'Diagnostic & Root Cause Agent: Analyzing logs.'],
    auditTrail: ['Incident created by monitoring system.', 'Intake Agent initiated case.', 'Knowledge Agent started search.'],
    terminalLog: `> Connecting to Production DB cluster...\n> Error: Connection Timeout on port 5432\n> Diagnostic Agent: Analyzing pgbouncer logs...\n> Found IP block on firewall rule #8492.`,
  },
  {
    id: 'INC002',
    title: 'Web server latency spike - US-East',
    status: 'pending_human',
    severity: 'high',
    metrics: { cpu: '98%', memory: '15GB', latency: '2500ms' },
    agentActivity: ['Intake & Triage Agent: Prioritized as high.', 'Diagnostic & Root Cause Agent: Identified potential memory leak.', 'Action & Remediation Agent: Proposed restart, awaiting approval.'],
    rootCause: 'Memory leak in Apache process causing massive swap usage.',
    proposedSolution: 'Restart Apache service and deploy temporary memory limit override.',
    auditTrail: ['Monitoring alert received.', 'Diagnostic Agent identified cause.', 'Approval requested for remediation.'],
    terminalLog: `> Analyzing top processes...\n> PID 4921 (apache2) consuming 98% CPU\n> Memory tracing initiated...\n> Memory leak confirmed in module mod_proxy.\n> Action Agent: Preparing restart script.`,
    codeSnippet: `#!/bin/bash\n# Remediation Script Generated by Action Agent\nsudo systemctl restart apache2\nsudo systemctl status apache2 --no-pager\necho "Service restarted and metrics stabilizing."`
  },
  {
    id: 'INC003',
    title: 'Minor CPU utilization increase on dev server',
    status: 'resolved',
    severity: 'low',
    metrics: { cpu: '70%', memory: '4GB', latency: '40ms' },
    agentActivity: ['Intake & Triage Agent: Classified as low.', 'Diagnostic & Root Cause Agent: Detected background job.', 'Action & Remediation Agent: Optimized cron job schedule.'],
    rootCause: 'Inefficient scheduled cron job colliding with DB backup',
    proposedSolution: 'Adjust cron job frequency and resource limits.',
    auditTrail: ['Incident resolved automatically.', 'Communication Agent updated ITSM ticket.'],
  },
  {
    id: 'INC004',
    title: 'Authentication service intermittent failures',
    status: 'active',
    severity: 'critical',
    metrics: { cpu: '85%', memory: '8GB', latency: '1200ms' },
    agentActivity: ['Intake & Triage Agent: High priority.', 'Diagnostic & Root Cause Agent: Suspects recent deploy impact.', 'Knowledge & Context Agent: Gathering rollback procedures.'],
    auditTrail: ['User reports received.', 'Incident escalated due to impact.', 'Agents collaborating.'],
  },
];

const agentIcons = {
  'Intake & Triage Agent': <Activity className="w-5 h-5 text-purple-400" />,
  'Knowledge & Context Agent': <Brain className="w-5 h-5 text-blue-400" />,
  'Diagnostic & Root Cause Agent': <Handshake className="w-5 h-5 text-yellow-400" />,
  'Action & Remediation Agent': <Terminal className="w-5 h-5 text-red-400" />,
  'Communication & Update Agent': <Mail className="w-5 h-5 text-green-400" />,
};

const Dashboard = () => {
  const [activeIncidents, setActiveIncidents] = useState<Incident[]>(mockIncidents);
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [reasoningLog, setReasoningLog] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState<'overview' | 'terminal' | 'code'>('overview');

  useEffect(() => {
    // Simulate live reasoning log updates
    const interval = setInterval(() => {
      const newLogEntry = `[${new Date().toLocaleTimeString()}] Agent ${Math.random() > 0.5 ? 'Diagnostic' : 'Knowledge'} processing data for INC${Math.floor(Math.random() * 4) + 1}.`;
      setReasoningLog((prev) => [...prev, newLogEntry].slice(-20)); // Keep last 20 entries
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const getStatusIcon = (status: Incident['status']) => {
    switch (status) {
      case 'active':
      case 'investigating':
        return <Activity className="w-5 h-5 text-primary" />;
      case 'resolved':
        return <CheckCircle className="w-5 h-5 text-success" />;
      case 'pending_human':
        return <UserCheck className="w-5 h-5 text-warning" />;
      default:
        return <MoreHorizontal className="w-5 h-5 text-secondary" />;
    }
  };

  const getSeverityClass = (severity: Incident['severity']) => {
    switch (severity) {
      case 'critical':
        return 'text-danger';
      case 'high':
        return 'text-warning';
      case 'medium':
        return 'text-primary';
      case 'low':
        return 'text-success';
      default:
        return 'text-foreground';
    }
  };

  const handleApproveRemediation = (incidentId: string) => {
    setActiveIncidents((prev) =>
      prev.map((inc) =>
        inc.id === incidentId
          ? { ...inc, status: 'resolved', agentActivity: [...inc.agentActivity, 'Action & Remediation Agent: Human approved fix. Communication & Update Agent: Marking as resolved.'] }
          : inc
      )
    );
    setSelectedIncident((prev) => (prev?.id === incidentId ? { ...prev, status: 'resolved' } : prev));
    setReasoningLog((prev) => [...prev, `[${new Date().toLocaleTimeString()}] Human approved remediation for ${incidentId}.`]);
  };

  return (
    <div className="flex flex-col min-h-[calc(100vh-64px)] p-6 bg-background text-foreground">
      <h1 className="text-3xl font-bold mb-6">SynaPath AI Dashboard</h1>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 flex-grow">
        {/* Global Incident View */}
        <div className="md:col-span-2 bg-card rounded-lg shadow-lg p-6 flex flex-col border border-border">
          <h2 className="text-2xl font-semibold mb-4">Global Incident View</h2>
          <div className="overflow-x-auto flex-grow">
            {activeIncidents.length === 0 ? (
              <p className="text-secondary">No active incidents.</p>
            ) : (
              <table className="w-full text-left table-auto">
                <thead>
                  <tr className="border-b border-border text-secondary">
                    <th className="py-2 px-4">ID</th>
                    <th className="py-2 px-4">Title</th>
                    <th className="py-2 px-4">Status</th>
                    <th className="py-2 px-4">Severity</th>
                    <th className="py-2 px-4">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {activeIncidents.map((incident) => (
                    <tr key={incident.id} className="border-b border-border last:border-b-0 hover:bg-background/50 transition-colors">
                      <td className="py-3 px-4 text-sm font-mono text-primary">{incident.id}</td>
                      <td className="py-3 px-4 text-sm font-medium">{incident.title}</td>
                      <td className="py-3 px-4 flex items-center gap-2 text-sm">
                        {getStatusIcon(incident.status)}
                        <span className="capitalize">{incident.status.replace(/_/g, ' ')}</span>
                      </td>
                      <td className={`py-3 px-4 text-sm font-semibold uppercase ${getSeverityClass(incident.severity)}`}>{incident.severity}</td>
                      <td className="py-3 px-4">
                        <button
                          onClick={() => { setSelectedIncident(incident); setActiveTab('overview'); }}
                          className="bg-primary hover:bg-indigo-600 text-white py-1.5 px-4 rounded-md text-xs font-semibold transition-colors shadow-md"
                        >
                          View Details
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        {/* Agent Status HUD */}
        <div className="md:col-span-1 bg-card rounded-lg shadow-lg p-6 flex flex-col border border-border">
          <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2"><Activity className="w-6 h-6 text-primary"/> Agent Status HUD</h2>
          <div className="flex flex-col gap-3 overflow-y-auto flex-grow pr-2">
            {Object.entries(agentIcons).map(([agentName, icon]) => (
              <div key={agentName} className="bg-background/80 p-3 rounded-lg shadow-sm flex items-center space-x-3 border border-border hover:border-primary/50 transition-colors">
                <div className="p-2 rounded-full bg-card border border-border">
                  {icon}
                </div>
                <div>
                  <h3 className="font-semibold text-sm">{agentName}</h3>
                  <p className="text-xs text-success flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-success animate-pulse"></span> Active</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Enhanced Incident Details Panel */}
        {selectedIncident && (
          <div className="md:col-span-3 bg-card rounded-lg shadow-xl p-0 flex flex-col border border-border overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Header */}
            <div className="bg-background p-6 border-b border-border flex justify-between items-start">
              <div>
                <h2 className="text-3xl font-bold flex items-center gap-3">
                  {selectedIncident.id} 
                  <span className={`text-sm px-3 py-1 rounded-full uppercase border ${getSeverityClass(selectedIncident.severity)} border-current`}>
                    {selectedIncident.severity}
                  </span>
                </h2>
                <p className="text-secondary mt-1 text-lg">{selectedIncident.title}</p>
              </div>
              <button onClick={() => setSelectedIncident(null)} className="text-secondary hover:text-danger transition-colors p-2">
                <XCircle className="w-8 h-8" />
              </button>
            </div>

            {/* Tabs */}
            <div className="flex border-b border-border bg-background/50 px-6">
              <button 
                onClick={() => setActiveTab('overview')} 
                className={`py-4 px-6 font-semibold text-sm flex items-center gap-2 border-b-2 transition-colors ${activeTab === 'overview' ? 'border-primary text-primary' : 'border-transparent text-secondary hover:text-foreground'}`}
              >
                <Info className="w-4 h-4" /> Overview
              </button>
              <button 
                onClick={() => setActiveTab('terminal')} 
                className={`py-4 px-6 font-semibold text-sm flex items-center gap-2 border-b-2 transition-colors ${activeTab === 'terminal' ? 'border-primary text-primary' : 'border-transparent text-secondary hover:text-foreground'}`}
              >
                <Terminal className="w-4 h-4" /> Agent Terminal
              </button>
              <button 
                onClick={() => setActiveTab('code')} 
                className={`py-4 px-6 font-semibold text-sm flex items-center gap-2 border-b-2 transition-colors ${activeTab === 'code' ? 'border-primary text-primary' : 'border-transparent text-secondary hover:text-foreground'}`}
              >
                <Code2 className="w-4 h-4" /> Proposed Fix
              </button>
            </div>

            {/* Tab Content */}
            <div className="p-6">
              {activeTab === 'overview' && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-sm uppercase text-secondary font-semibold mb-2">Affected Systems Metrics</h3>
                      <div className="flex gap-4">
                        <div className="bg-background px-4 py-3 rounded-lg border border-border text-center min-w-[100px]">
                          <p className="text-xs text-secondary mb-1">CPU</p>
                          <p className="text-xl font-mono font-bold text-danger">{selectedIncident.metrics.cpu}</p>
                        </div>
                        <div className="bg-background px-4 py-3 rounded-lg border border-border text-center min-w-[100px]">
                          <p className="text-xs text-secondary mb-1">Memory</p>
                          <p className="text-xl font-mono font-bold text-warning">{selectedIncident.metrics.memory}</p>
                        </div>
                        <div className="bg-background px-4 py-3 rounded-lg border border-border text-center min-w-[100px]">
                          <p className="text-xs text-secondary mb-1">Latency</p>
                          <p className="text-xl font-mono font-bold text-primary">{selectedIncident.metrics.latency}</p>
                        </div>
                      </div>
                    </div>
                    <div>
                      <h3 className="text-sm uppercase text-secondary font-semibold mb-2">Root Cause Analysis</h3>
                      <p className="bg-background p-4 rounded-lg border border-border text-foreground">
                        {selectedIncident.rootCause || 'Diagnostic Agent is still analyzing telemetry data...'}
                      </p>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-sm uppercase text-secondary font-semibold mb-2">Agent Audit Trail</h3>
                    <div className="space-y-3">
                      {selectedIncident.agentActivity.map((activity, index) => (
                        <div key={index} className="flex gap-3 items-start">
                          <div className="mt-1"><CheckCircle className="w-4 h-4 text-primary" /></div>
                          <p className="text-sm text-foreground bg-background p-2 rounded-md border border-border w-full">{activity}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {activeTab === 'terminal' && (
                <div className="bg-[#0D1117] rounded-lg p-4 font-mono text-sm text-green-400 border border-border h-64 overflow-y-auto shadow-inner">
                  <div className="flex gap-2 mb-4">
                    <div className="w-3 h-3 rounded-full bg-red-500"></div>
                    <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                    <div className="w-3 h-3 rounded-full bg-green-500"></div>
                  </div>
                  <pre className="whitespace-pre-wrap">{selectedIncident.terminalLog || '> Awaiting diagnostic stream...'}</pre>
                  <div className="animate-pulse mt-2">_</div>
                </div>
              )}

              {activeTab === 'code' && (
                <div className="flex flex-col h-full">
                  <div className="bg-[#1E1E1E] rounded-lg p-6 font-mono text-sm text-blue-300 border border-border h-64 overflow-y-auto shadow-inner mb-6">
                    <pre className="whitespace-pre-wrap">{selectedIncident.codeSnippet || '// No code remediation proposed for this incident.'}</pre>
                  </div>
                  
                  {selectedIncident.status === 'pending_human' && selectedIncident.proposedSolution && (
                    <div className="bg-warning/10 border border-warning/30 p-4 rounded-lg flex items-center justify-between">
                      <div>
                        <h4 className="font-bold text-warning flex items-center gap-2"><AlertTriangle className="w-5 h-5"/> Human Approval Required</h4>
                        <p className="text-sm text-foreground mt-1">Agent proposes executing the above script on target servers.</p>
                      </div>
                      <div className="flex gap-3">
                        <button className="bg-background border border-border hover:bg-card text-foreground py-2 px-6 rounded-md font-semibold transition-colors">
                          Reject Fix
                        </button>
                        <button 
                          onClick={() => handleApproveRemediation(selectedIncident.id)}
                          className="bg-success hover:bg-green-600 text-white py-2 px-6 rounded-md font-bold transition-colors shadow-lg hover:shadow-green-500/20"
                        >
                          Execute Remediation
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default Dashboard;
